spring:
  redis:
    host: auth-service-db
    password: ${AUTH_SERVICE_DB_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    prefer-ip-address: true

security:
  jwt:
    access-token:
      secret: ${AUTH_SERVICE_ACCESS_TOKEN_SECRET}
      expiration: 900
    refresh-token:
      secret: ${AUTH_SERVICE_REFRESH_TOKEN_SECRET}
      expiration: 604800
